# Generated by Django 2.2b1 on 2019-05-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Id', models.CharField(max_length=20)),
                ('Category_Name', models.CharField(max_length=20)),
                ('Category_Type', models.CharField(max_length=20)),
                ('Category_Description', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
    ]
