# Generated by Django 2.2b1 on 2019-05-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Category_Id',
        ),
    ]
