# Generated by Django 2.2b1 on 2019-05-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Category_Description',
        ),
    ]
