# Generated by Django 2.2b1 on 2019-05-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_emp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emp',
            new_name='Products',
        ),
    ]
