# Generated by Django 2.2b1 on 2019-05-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190528_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='dept',
        ),
    ]
