# Generated by Django 2.2b1 on 2019-05-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_products_dept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
