# Generated by Django 2.2b1 on 2019-05-28 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=20)),
                ('Product_Image', models.CharField(max_length=20)),
                ('Product_Price', models.FloatField(default=12000)),
                ('Product_Description', models.CharField(max_length=20)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Category')),
            ],
        ),
    ]
