# Generated by Django 2.2b1 on 2019-05-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.IntegerField(default=100)),
                ('cvvno', models.IntegerField(default=100)),
                ('expiryDate', models.CharField(max_length=20)),
                ('amount', models.FloatField(default=100)),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
    ]
