# Generated by Django 2.2b1 on 2019-05-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiryDate',
            field=models.IntegerField(max_length=20),
        ),
    ]
