# Generated by Django 2.2b1 on 2019-05-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190530_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiryDate',
            field=models.CharField(max_length=20),
        ),
    ]
